# Generated by Django 6.0.4 on 2026-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(default='', max_length=5)),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('st_abbr', models.CharField(max_length=50)),
            ],
        ),
    ]
